anguage: c
dist: trusty
sudo: true

script:
  - sudo apt-get -y install expect dnsutils lintian fakeroot wget
  - ( ./configure --prefix=/usr --disable-seccomp && make && sudo make install && sudo make test-travis )
